# Generated by Django 2.2.8 on 2019-12-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('CID', models.IntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Main_Telephone_Number', models.CharField(max_length=25)),
                ('Other_Telephone_Number', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
