# Generated by Django 2.2.8 on 2019-12-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntnbms', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Video_File',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
